### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by davep3rrett** [amirandalibi/cashew#1]
Hey @amirandalibi - we want to fork this and modify to use the `users/self` endpoint. Would you mind choosing an open source license for this so we can keep using Cashew in good conscience? Thank you sir 🙏 🎩 

https://choosealicense.com/

**Comment by amirandalibi** [comment]
Thanks @davep3rrett for bringing this up, I've gone ahead and added `MIT` license to the project.
I've been meaning to change the endpoint to `self` since Instagram is not supporting other endpoints anymore.
I might do that in the upcoming days.
